name: Deploy Production Build to EC2

on:
  push:
    branches:
      - master  # Trigger the workflow only on pushes to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Step 2: Set up SSH access
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    # Step 3: Copy the dist folder to EC2 instance
    - name: Copy dist folder to EC2
      run: |
        scp -r ./dist/* ubuntu@ec2-13-232-9-77.ap-south-1.compute.amazonaws.com:/var/www/html/rareminds/dist/

    # Step 4: Restart the application (e.g., using PM2 or similar)
    - name: Restart Application on EC2
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@ec2-13-232-9-77.ap-south-1.compute.amazonaws.com << 'EOF'
        cd /var/www/html/rareminds/dist
        pm2 restart all
        EOF
