name: Deploy Production Build to EC2

on:
  push:
    branches:
      - dev  # Trigger the workflow only on pushes to the 'dev' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Step 2: Set up SSH access
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    # Step 3: Remove the entire dist directory on EC2
    - name: Remove dist folder on EC2
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@ec2-13-232-9-77.ap-south-1.compute.amazonaws.com << 'EOF'
        # Remove the entire dist folder
        sudo rm -rf /var/www/html/rareminds/dist
        EOF

    # Step 4: Copy the entire dist folder to EC2 instance
    - name: Copy dist folder to EC2
      run: |
        scp -r ./dist ubuntu@ec2-13-232-9-77.ap-south-1.compute.amazonaws.com:/var/www/html/rareminds/

    # Step 5: Restart Application on EC2 and Execute Additional Commands
    - name: Restart Application on EC2 and Execute Additional Command
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@ec2-13-232-9-77.ap-south-1.compute.amazonaws.com << 'EOF'
        cd /var/www/html/rareminds/dist
        pm2 restart all
        # Additional command (e.g., clear application cache, etc.)
        sudo rm -rf /var/www/html/rareminds/cache/*
        EOF
